<?xml version="1.0" ?>

<!DOCTYPE CityInfo [
   <!ELEMENT CityInfo (Government, Neighborhood+)>
   <!ATTLIST CityInfo Name CDATA #REQUIRED>
   <!ELEMENT Government (Mayor, Assistant)>
   <!ELEMENT Mayor (#PCDATA)>
   <!ELEMENT Assistant (#PCDATA)>
   <!ELEMENT Neighborhood (Library | Bookshop)?>
   <!ATTLIST Neighborhood Name CDATA #REQUIRED>
   <!ELEMENT Library (#PCDATA)>
   <!ELEMENT Bookshop (#PCDATA)>
]>

<CityInfo Name="Berkeley">
	<Government>
	<Mayor>Bates</Mayor>
	<Assistant>Ortiz</Assistant>
	</Government>
	<Neighborhood Name="1">
	</Neighborhood>
	<Neighborhood Name="2">
	<Bookshop></Bookshop>
	</Neighborhood>
	<Neighborhood Name="3">
	</Neighborhood>
	<Neighborhood Name="4">
	</Neighborhood>
</CityInfo>